version: '3.8'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=toolz_crud
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: